name: GUTILS_mod
channels:
  - conda-forge
dependencies:
- cc-plugin-glider>=1.0.4
- compliance-checker
- gsw<3.1.0
- netCDF4
- numpy>=1.14
- pandas
- pocean-core>=1.3.3,<2.0
- pyinotify
- scipy
- six
- whichcraft
- pip
- pip:
    - git+https://gitlab.oceantrack.org/ceotr-public/dinkum.git@GD-57
